### ISSUE TITLE
locals: {action: nil} now results in undefined local variable or method.

### ISSUE THREAD

**Issue by rubys** [hotwired/turbo-rails#570]
Upgrading a rails 7.1 project that uses `broadcast_replace_to` to turbo-rails 2/turbo 8, resulted in the following test failure:

```
ActionView::Template::Error: undefined local variable or method `action' for an instance of #<Class:0x000000011ef58ad8>
    app/views/scores/_last_update.html.erb:1
```

In my case, setting `locals: {action: false}` will achieve the desired result, so I have a workaround, but previously I could set a local variable to `nil`.  I've yet to find any docs that indicate that this is an intentional change in behavior.

If it helps, doing a git bisect identified the following as the change that broke this:

* https://github.com/hotwired/turbo-rails/commit/7800f38ee94247bd28362a4fd9de850b66ee0858

And links to the code that this change broke:

* https://github.com/rubys/showcase/blob/cb5d064f8152a5b6bd47b0c184b1431a9c734c37/app/models/score.rb#L8-L10
* https://github.com/rubys/showcase/blob/cb5d064f8152a5b6bd47b0c184b1431a9c734c37/app/views/scores/_last_update.html.erb

While turbo 8 provides other means by which this could be implemented, my impression was that this should continue to work.

**Comment by jjongs08** [comment]
I am also using broadcast_append_later_to, but I am experiencing the same issue.

It seems that the problem is caused by a change in the logic of the broadcast_rendering_with_defaults method.

Can someone explain why compact is used in [this code](https://github.com/hotwired/turbo-rails/compare/v1.5.0...v2.0.0-beta.1#diff-5956b6256febdc6ef2d3a5fe18f05cc7449578d891022b1d5d439fba803643c2R427)?

**Comment by shanereddy** [comment]
I am experiencing the same issue after upgrading to 2.0.5.

**Comment by brunoprietog** [comment]
I've merged #720, so I'm closing this one, but let me know if that doesn't work and I'll reopen it.
