### ISSUE TITLE
Regression when upgrading from 0.5.9 to 0.5.11 

### ISSUE THREAD

**Issue by jcoyne** [hotwired/turbo-rails#185]
```
ActionView::Template::Error (undefined method `collection' for #<Collection:0x00007fb2c0283cf8>
Did you mean?  collection_versions):
    1: <% # The collection details page %>
    2: <section id="<%= dom_id(collection_version.collection) %>">
    3:   <%= render Collections::Show::DetailsHeaderComponent.new(collection_version: collection_version) %>
    4:   <%= render Collections::InformationComponent.new(collection_version: collection_version) %>
    5:   <%= render Collections::DetailComponent.new(collection_version: collection_version) %>

    # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activemodel-6.1.3.2/lib/active_model/attribute_methods.rb:469:in `method_missing'
     # ./app/views/collection_versions/_collection_version.html.erb:2:in `_app_views_collection_versions__collection_version_html_erb__1822288999697966652_27660'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/base.rb:247:in `public_send'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/base.rb:247:in `_run'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/template.rb:154:in `block in render'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:205:in `instrument'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/template.rb:345:in `instrument_render_template'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/template.rb:152:in `render'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/object_renderer.rb:31:in `render_partial_template'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/partial_renderer.rb:271:in `render'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/object_renderer.rb:16:in `render_object_with_partial'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/renderer.rb:77:in `render_partial_to_object'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:117:in `block in _render_template'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/base.rb:273:in `in_rendering_context'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:116:in `_render_template'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/streaming.rb:218:in `_render_template'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:103:in `render_to_body'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.3.2/lib/abstract_controller/rendering.rb:47:in `render_to_string'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/rendering.rb:41:in `render_to_string'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/renderer.rb:100:in `render'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/rendering.rb:11:in `render'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/turbo-rails-0.5.11/app/channels/turbo/streams/broadcasts.rb:80:in `render_format'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/turbo-rails-0.5.11/app/channels/turbo/streams/broadcasts.rb:34:in `broadcast_action_to'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/turbo-rails-0.5.11/app/channels/turbo/streams/broadcasts.rb:13:in `broadcast_replace_to'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/turbo-rails-0.5.11/app/models/concerns/turbo/broadcastable.rb:98:in `broadcast_replace_to'
     # ./app/models/collection.rb:29:in `broadcast_update'
     # ./app/models/collection_version.rb:12:in `block in <class:CollectionVersion>'
```

I also upgraded to `    "@hotwired/turbo-rails": "^7.0.0-beta.7",` at the same time.

In `app/models/collection.rb` in the `broadcase_update()` method I have the following code:

```ruby
    broadcast_replace_to self, :details, partial: 'collection_versions/collection_version',
                                         locals: { collection_version: head }
```

**Comment by jcoyne** [comment]
@alexandreruban Are you able to tell if that line in #115 causes this?

**Comment by kwent** [comment]
I'm seeing a similar issue after upgrading

**Comment by dhh** [comment]
That backtrace seems to suggest this is all about methods on your own models that are called in your partial directly. Don’t see anything here that points to a change in turbo-rails. And upgrading the JS dependency wouldn’t have an effect here. But you can try depending on the git version, then stepping through the commits to see if you can nail it down to a change in this gem. Doesn’t seem like it though. Do reopen if you arrive at something.

**Comment by jcoyne** [comment]
@dhh I don't have the rights needed to reopen an issue, but my tests work with 2e20ce4 and then fail on 1864ed3

**Comment by jcoyne** [comment]
The problem is the reverse merge was eliminated so `o[:locals][:collection] = self` is no longer set.

**Comment by jcoyne** [comment]
I reopened this as #186
